language: node_js
os: linux
dist: focal
node_js:
  - '13.12.0'
cache: yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn global add @quasar/cli
install:
  - yarn
jobs:
  include:
    # all branches
    - stage: Development - Lint, Test, & Build
      if: branch != master
      script:
        - yarn lint
        - yarn test:unit
        - yarn build
        - yarn build:pwa
    # master branch only
    - stage: Production(master) - Lint, Test, Build, Upload coverage, Deploy to gh-pages
      if: branch = master
      script:
        - yarn lint
        - yarn test:unit
        - yarn build
        - yarn build:pwa
        - npm install -g codecov
        - bash <(curl -s https://codecov.io/bash)
